/**
 * ShoppingListScreen — display-only checklist.
 * Receives the full stack object from StackDetailScreen via route.params.stack.
 * Shows items as a checklist + stack summary totals.
 * No frontend math. All totals are backend-provided.
 */
import React, { useState } from 'react';
import {
  View, Text, StyleSheet, ScrollView, TouchableOpacity,
  StatusBar, Share, Platform, Linking,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Feather } from '@expo/vector-icons';
import { resolveCouponActivationLink } from '../src/lib/retailerCouponLinks';

// ── Brand ─────────────────────────────────────────────────────────────────────
const GREEN      = '#0C9E54';
const FOREST     = '#04361D';
const NAVY       = '#1A237E';
const WHITE      = '#FFFFFF';
const MINT       = '#F0FBF0';
const MINT_DEEP  = '#E8F5E9';
const SLATE      = '#64748B';
const BORDER     = '#E2E8F0';
const LIGHT_GRN  = '#DCFCE7';

// ── Helpers ───────────────────────────────────────────────────────────────────
function fmtCents(cents) {
  if (cents == null || isNaN(cents)) return '$—';
  return `$${(Math.max(0, Number(cents)) / 100).toFixed(2)}`;
}

function parseMaybeJson(val, fallback = []) {
  if (Array.isArray(val)) return val;
  if (typeof val === 'string') {
    try { return JSON.parse(val); } catch { return fallback; }
  }
  return fallback;
}

function centsFrom(value) {
  const n = Number(value);
  if (!Number.isFinite(n) || n <= 0) return 0;
  return n < 500 ? Math.round(n * 100) : Math.round(n);
}

function itemName(item) {
  return String(
    item.display_name ??
    item.displayName ??
    item.name ??
    item.item ??
    item.product_name ??
    'Item'
  );
}

function couponSearchName(item) {
  return item.coupon_search_name ?? item.couponSearchName ?? null;
}

function couponValueCents(item) {
  return centsFrom(item.coupon_value_cents ?? item.couponValueCents ?? item.coupon ?? 0);
}

function regularPriceCents(item) {
  return centsFrom(item.price_cents ?? item.regular_price_cents ?? item.regularPriceCents ?? item.regular_price ?? item.price);
}

function finalPriceCents(item) {
  return centsFrom(item.final_price_cents ?? item.finalPriceCents ?? item.final_price ?? item.pay_price ?? item.price);
}

function quantity(item) {
  const q = Number(item.qty ?? item.quantity ?? 1);
  return Number.isFinite(q) && q > 0 ? q : 1;
}

async function openUrl(url) {
  if (!url) return;
  try {
    await Linking.openURL(url);
  } catch {
    // The official retailer app/site is still the source of truth; failures are non-fatal.
  }
}

// ── Main screen ───────────────────────────────────────────────────────────────
export default function ShoppingListScreen({ route, navigation }) {
  const stack = route?.params?.stack;
  const [checked, setChecked] = useState({});

  if (!stack) {
    return (
      <View style={[s.container, { alignItems: 'center', justifyContent: 'center' }]}>
        <Feather name="alert-circle" size={36} color={SLATE} />
        <Text style={{ color: SLATE, marginTop: 12 }}>No shopping list data.</Text>
        <TouchableOpacity onPress={() => navigation.goBack()} style={{ marginTop: 20 }}>
          <Text style={{ color: GREEN, fontWeight: '700' }}>Go back</Text>
        </TouchableOpacity>
      </View>
    );
  }

  const items = parseMaybeJson(stack.breakdown_list ?? stack.stack_items ?? stack.items, []);
  const finalCents    = stack.final_out_of_pocket_cents ?? 0;
  const subtotalCents = stack.subtotal_cents ?? 0;
  const discountCents = stack.total_discounts_cents ?? 0;
  const savingsPct    = stack.savings_percent ?? 0;
  const store         = stack.store || 'Store';
  const retailer      = stack.retailer || stack.store || stack.retailer_key;

  const toggleItem = (idx) => setChecked(prev => ({ ...prev, [idx]: !prev[idx] }));

  const checkedCount  = Object.values(checked).filter(Boolean).length;
  const allDone       = items.length > 0 && checkedCount === items.length;

  const handleShare = async () => {
    const lines = items.map((item, i) =>
      `${checked[i] ? '✅' : '☐'} ${itemName(item)} — ${fmtCents(finalPriceCents(item) || regularPriceCents(item))}`
    );
    const msg = [
      `🛒 ${stack.title || store + ' Stack'} — Snippd Shopping List`,
      '',
      lines.join('\n'),
      '',
      `Subtotal: ${fmtCents(subtotalCents)}`,
      `Est. savings: -${fmtCents(discountCents)}`,
      `Final: ${fmtCents(finalCents)}`,
      '',
      'Generated by Snippd — snippd.com',
    ].join('\n');
    try { await Share.share({ message: msg }); } catch { /* cancelled */ }
  };

  return (
    <View style={s.container}>
      <StatusBar barStyle="dark-content" />

      {/* ── Header ──────────────────────────────────────────────────────────── */}
      <SafeAreaView style={s.headerShell} edges={['top']}>
        <View style={s.navRow}>
          <TouchableOpacity style={s.backBtn} onPress={() => navigation.goBack()}>
            <Feather name="arrow-left" size={20} color={NAVY} />
          </TouchableOpacity>
          <View style={{ flex: 1 }}>
            <Text style={s.headerTitle}>My Shopping List</Text>
            <Text style={s.headerSub}>{items.length} item{items.length !== 1 ? 's' : ''} · {store}</Text>
          </View>
          <TouchableOpacity style={s.shareHeaderBtn} onPress={handleShare}>
            <Feather name="share-2" size={18} color={NAVY} />
          </TouchableOpacity>
        </View>
      </SafeAreaView>

      <ScrollView
        style={{ flex: 1 }}
        contentContainerStyle={s.scroll}
        showsVerticalScrollIndicator={false}
      >
        {/* ── Stack label ──────────────────────────────────────────────────── */}
        <View style={s.stackLabel}>
          <View style={s.stackLabelDot} />
          <Text style={s.stackLabelTxt}>{stack.title || store + ' Stack'}</Text>
          {checkedCount > 0 && (
            <View style={s.progressPill}>
              <Text style={s.progressPillTxt}>{checkedCount}/{items.length}</Text>
            </View>
          )}
        </View>

        {/* ── SHOPPING CHECKLIST section ────────────────────────────────────── */}
        <Text style={s.sectionTitle}>SHOPPING CHECKLIST</Text>

        {items.length === 0 ? (
          <View style={s.emptyCard}>
            <Feather name="inbox" size={32} color={SLATE} />
            <Text style={s.emptyTxt}>No items in this stack.</Text>
          </View>
        ) : (
          <View style={s.listCard}>
            {items.map((item, i) => {
              const isChecked = !!checked[i];
              const isCoupon  = item.coupon_status === 'verified';
              const price     = finalPriceCents(item) || regularPriceCents(item);
              const regular   = regularPriceCents(item);
              const couponName = couponSearchName(item);
              const couponCents = couponValueCents(item);
              const qty = quantity(item);
              const couponLink = resolveCouponActivationLink(item, retailer);
              return (
                <TouchableOpacity
                  key={i}
                  style={[s.listRow, isChecked && s.listRowChecked,
                    i === items.length - 1 && { borderBottomWidth: 0 }]}
                  onPress={() => toggleItem(i)}
                  activeOpacity={0.75}
                >
                  {/* Checkbox */}
                  <View style={[s.checkbox, isChecked && s.checkboxChecked]}>
                    {isChecked && <Feather name="check" size={11} color={WHITE} />}
                  </View>

                  {/* Content */}
                  <View style={{ flex: 1 }}>
                    <Text style={[s.itemName, isChecked && s.itemNameChecked]}>
                      {itemName(item)}
                    </Text>
                    {couponName ? (
                      <View style={s.couponRow}>
                        <Feather name="scissors" size={10} color={isCoupon ? GREEN : SLATE} />
                        <Text style={[s.couponTxt, !isCoupon && { color: SLATE }]}>
                          {couponName}
                        </Text>
                        {isCoupon && (
                          <View style={s.verifiedBadge}>
                            <Text style={s.verifiedTxt}>VERIFIED</Text>
                          </View>
                        )}
                      </View>
                    ) : null}
                    {couponCents > 0 && (
                      <Text style={s.couponValue}>-{fmtCents(couponCents)} coupon</Text>
                    )}
                    {item.coupon_clip_instruction ? (
                      <Text style={s.clipInstruction} numberOfLines={1}>
                        {item.coupon_clip_instruction}
                      </Text>
                    ) : null}
                    {couponLink.url ? (
                      <TouchableOpacity
                        style={s.couponLinkBtn}
                        onPress={() => openUrl(couponLink.url)}
                        activeOpacity={0.85}
                      >
                        <Feather name="external-link" size={10} color={GREEN} />
                        <Text style={s.couponLinkTxt}>{couponLink.label}</Text>
                      </TouchableOpacity>
                    ) : null}
                  </View>

                  {/* Price */}
                  <View style={s.priceCol}>
                    {regular > 0 && regular !== price && (
                      <Text style={s.strikePrice}>{fmtCents(regular)}</Text>
                    )}
                    <Text style={[s.itemPrice, isChecked && { color: SLATE }]}>
                      {fmtCents(price)}
                    </Text>
                    {qty > 1 && (
                      <Text style={s.qtyTxt}>×{qty}</Text>
                    )}
                  </View>
                </TouchableOpacity>
              );
            })}
          </View>
        )}

        {/* ── Stack Summary ─────────────────────────────────────────────────── */}
        <View style={s.summaryCard}>
          <Text style={s.sectionTitle}>STACK SUMMARY</Text>
          <View style={s.summaryRow}>
            <Text style={s.summaryLabel}>Subtotal</Text>
            <Text style={s.summaryVal}>{fmtCents(subtotalCents)}</Text>
          </View>
          <View style={s.summaryRow}>
            <Text style={s.summaryLabel}>Est. Coupon Savings</Text>
            <Text style={[s.summaryVal, { color: GREEN }]}>-{fmtCents(discountCents)}</Text>
          </View>
          {savingsPct > 0 && (
            <View style={s.summaryRow}>
              <Text style={s.summaryLabel}>Savings %</Text>
              <Text style={[s.summaryVal, { color: GREEN }]}>{savingsPct}%</Text>
            </View>
          )}
          <View style={[s.summaryRow, s.summaryTotal]}>
            <Text style={s.totalLabel}>TOTAL OUT OF POCKET</Text>
            <Text style={s.totalVal}>{fmtCents(finalCents)}</Text>
          </View>
        </View>

        {/* ── Action buttons ────────────────────────────────────────────────── */}
        <View style={s.actionRow}>
          <TouchableOpacity
            style={s.secondaryBtn}
            onPress={() => navigation.goBack()}
            activeOpacity={0.85}
          >
            <Feather name="eye" size={16} color={FOREST} />
            <Text style={s.secondaryBtnTxt}>View Stack Details</Text>
          </TouchableOpacity>

          <TouchableOpacity
            style={s.primaryBtn}
            onPress={() => navigation.navigate('TripSummaryFeedback', {
              planned_total_cents:    finalCents,
              receipt_total_cents:    0,
              verified_savings_cents: discountCents,
              coupons_clipped:        items.filter(i => i.coupon_status === 'verified').length,
              plan_followed_pct:      checkedCount > 0
                                        ? Math.round((checkedCount / items.length) * 100)
                                        : 0,
              store,
            })}
            activeOpacity={0.85}
          >
            <Feather name="check-circle" size={16} color={WHITE} />
            <Text style={s.primaryBtnTxt}>View Summary</Text>
          </TouchableOpacity>
        </View>

        {/* ── Reminder strip ────────────────────────────────────────────────── */}
        <View style={s.reminderStrip}>
          {['Always Up to Date', 'Shop Smart', 'Earn Rewards', 'Personalized For You'].map((t, i) => (
            <View key={i} style={s.reminderItem}>
              <View style={s.reminderDot} />
              <Text style={s.reminderTxt}>{t.toUpperCase()}</Text>
            </View>
          ))}
        </View>

        <View style={{ height: 40 }} />
      </ScrollView>
    </View>
  );
}

// ── Styles ────────────────────────────────────────────────────────────────────
const s = StyleSheet.create({
  container:      { flex: 1, backgroundColor: MINT },

  headerShell:    { backgroundColor: WHITE, borderBottomWidth: 1, borderBottomColor: BORDER, paddingBottom: 12, paddingHorizontal: 16 },
  navRow:         { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 6 },
  backBtn:        { width: 36, height: 36, borderRadius: 10, backgroundColor: MINT_DEEP, alignItems: 'center', justifyContent: 'center' },
  shareHeaderBtn: { width: 36, height: 36, borderRadius: 10, backgroundColor: MINT_DEEP, alignItems: 'center', justifyContent: 'center' },
  headerTitle:    { fontSize: 17, fontWeight: '800', color: NAVY },
  headerSub:      { fontSize: 12, color: SLATE, marginTop: 1 },

  scroll:         { paddingHorizontal: 16, paddingTop: 16, gap: 12, paddingBottom: 40 },

  stackLabel:     { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: WHITE, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 10, borderWidth: 1, borderColor: BORDER },
  stackLabelDot:  { width: 8, height: 8, borderRadius: 4, backgroundColor: GREEN },
  stackLabelTxt:  { flex: 1, fontSize: 13, fontWeight: '700', color: NAVY },
  progressPill:   { backgroundColor: LIGHT_GRN, borderRadius: 8, paddingHorizontal: 8, paddingVertical: 3 },
  progressPillTxt:{ fontSize: 11, fontWeight: '800', color: GREEN },

  sectionTitle:   { fontSize: 10, fontWeight: '800', color: SLATE, letterSpacing: 2, paddingHorizontal: 4, marginBottom: 2 },

  listCard:       { backgroundColor: WHITE, borderRadius: 16, overflow: 'hidden', borderWidth: 1, borderColor: BORDER },
  listRow:        { flexDirection: 'row', alignItems: 'flex-start', padding: 14, borderBottomWidth: 1, borderBottomColor: '#F1F5F9', gap: 10 },
  listRowChecked: { backgroundColor: '#FAFAFA', opacity: 0.6 },
  checkbox:       { width: 20, height: 20, borderRadius: 5, borderWidth: 2, borderColor: BORDER, alignItems: 'center', justifyContent: 'center', flexShrink: 0, marginTop: 2 },
  checkboxChecked:{ backgroundColor: GREEN, borderColor: GREEN },
  itemName:       { fontSize: 14, fontWeight: '700', color: NAVY, lineHeight: 20 },
  itemNameChecked:{ textDecorationLine: 'line-through', color: SLATE },
  couponRow:      { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 3, flexWrap: 'wrap' },
  couponTxt:      { fontSize: 11, color: GREEN, fontWeight: '600' },
  verifiedBadge:  { backgroundColor: LIGHT_GRN, borderRadius: 4, paddingHorizontal: 5, paddingVertical: 1 },
  verifiedTxt:    { fontSize: 9, fontWeight: '900', color: GREEN },
  couponValue:    { fontSize: 10, color: GREEN, fontWeight: '700', marginTop: 2 },
  clipInstruction:{ fontSize: 10, color: SLATE, marginTop: 2, fontStyle: 'italic' },
  couponLinkBtn:  { flexDirection: 'row', alignItems: 'center', gap: 5, alignSelf: 'flex-start', marginTop: 7, backgroundColor: LIGHT_GRN, borderRadius: 8, paddingHorizontal: 8, paddingVertical: 5 },
  couponLinkTxt:  { fontSize: 10, color: GREEN, fontWeight: '800' },
  priceCol:       { alignItems: 'flex-end', flexShrink: 0, gap: 1 },
  strikePrice:    { fontSize: 11, color: SLATE, textDecorationLine: 'line-through' },
  itemPrice:      { fontSize: 15, fontWeight: '800', color: NAVY },
  qtyTxt:         { fontSize: 10, color: SLATE },

  emptyCard:      { backgroundColor: WHITE, borderRadius: 16, padding: 32, alignItems: 'center', gap: 12, borderWidth: 1, borderColor: BORDER },
  emptyTxt:       { fontSize: 14, color: SLATE },

  summaryCard:    { backgroundColor: WHITE, borderRadius: 16, padding: 16, gap: 10, borderWidth: 1, borderColor: BORDER },
  summaryRow:     { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  summaryLabel:   { fontSize: 13, color: SLATE, fontWeight: '600' },
  summaryVal:     { fontSize: 15, fontWeight: '700', color: NAVY },
  summaryTotal:   { paddingTop: 10, marginTop: 4, borderTopWidth: 1, borderTopColor: BORDER },
  totalLabel:     { fontSize: 11, fontWeight: '800', color: NAVY, letterSpacing: 0.5 },
  totalVal:       { fontSize: 22, fontWeight: '900', color: NAVY },

  actionRow:      { flexDirection: 'row', gap: 10 },
  secondaryBtn:   { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, borderRadius: 12, borderWidth: 1.5, borderColor: FOREST, paddingVertical: 13 },
  secondaryBtnTxt:{ fontSize: 13, fontWeight: '700', color: FOREST },
  primaryBtn:     { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, backgroundColor: FOREST, borderRadius: 12, paddingVertical: 13 },
  primaryBtnTxt:  { fontSize: 13, fontWeight: '700', color: WHITE },

  reminderStrip:  { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: 10, paddingVertical: 10 },
  reminderItem:   { flexDirection: 'row', alignItems: 'center', gap: 5 },
  reminderDot:    { width: 5, height: 5, borderRadius: 3, backgroundColor: GREEN },
  reminderTxt:    { fontSize: 9, fontWeight: '800', color: SLATE, letterSpacing: 1 },
});
