// Seeded demo data for WeeklyDinnerPlanScreen
// All monetary values in cents. No external dependencies.

export const SEEDED_WEEKLY_PLAN = {
  weekly_plan_id: 'wp_001',
  user_id: null,
  week_start_date: '2026-05-11',
  week_end_date: '2026-05-17',
  household_size: 4,
  weekly_budget_cents: 22000,
  planned_total_cents: 19369,
  estimated_savings_cents: 2930,
  out_of_pocket_cents: 19369,
  best_overall_store_id: 'publix',
  best_shop_window_start: '2026-05-11',
  best_shop_window_end: '2026-05-17',
  deal_valid_until: 'May 17',
  plan_status: 'active',
};

export const SEEDED_DAY_PLANS = [
  {
    day_plan_id: 'dp_mon',
    day_of_week: 'Monday',
    date: '2026-05-11',
    daily_total_cents: 2750,
    daily_savings_cents: 520,
    meal_count: 3,
    best_store_id: 'publix',
    store_ids_used: ['aldi', 'publix'],
    summary_text: 'Light breakfast, quick lunch wrap, and a hearty Italian family dinner.',
  },
  {
    day_plan_id: 'dp_tue',
    day_of_week: 'Tuesday',
    date: '2026-05-12',
    daily_total_cents: 2480,
    daily_savings_cents: 390,
    meal_count: 3,
    best_store_id: 'publix',
    store_ids_used: ['aldi', 'publix'],
    summary_text: 'Protein-forward day with eggs, grilled cheese, and chicken stir fry.',
  },
  {
    day_plan_id: 'dp_wed',
    day_of_week: 'Wednesday',
    date: '2026-05-13',
    daily_total_cents: 2620,
    daily_savings_cents: 410,
    meal_count: 3,
    best_store_id: 'publix',
    store_ids_used: ['aldi', 'publix', 'walmart'],
    summary_text: 'Yogurt parfait, tuna wraps, and taco night — three-store value day.',
  },
  {
    day_plan_id: 'dp_thu',
    day_of_week: 'Thursday',
    date: '2026-05-14',
    daily_total_cents: 2940,
    daily_savings_cents: 480,
    meal_count: 3,
    best_store_id: 'publix',
    store_ids_used: ['aldi', 'publix'],
    summary_text: 'Pancake breakfast, Greek salad lunch, and premium salmon dinner.',
  },
  {
    day_plan_id: 'dp_fri',
    day_of_week: 'Friday',
    date: '2026-05-15',
    daily_total_cents: 2860,
    daily_savings_cents: 420,
    meal_count: 3,
    best_store_id: 'publix',
    store_ids_used: ['aldi', 'publix', 'walmart'],
    summary_text: 'French toast, BLT lunch, and Chicken Tikka Masala for Friday dinner.',
  },
  {
    day_plan_id: 'dp_sat',
    day_of_week: 'Saturday',
    date: '2026-05-16',
    daily_total_cents: 3120,
    daily_savings_cents: 490,
    meal_count: 3,
    best_store_id: 'publix',
    store_ids_used: ['aldi', 'publix', 'walmart'],
    summary_text: 'Weekend brunch omelette, club sandwich, and BBQ ribs for the family.',
  },
  {
    day_plan_id: 'dp_sun',
    day_of_week: 'Sunday',
    date: '2026-05-17',
    daily_total_cents: 2599,
    daily_savings_cents: 220,
    meal_count: 3,
    best_store_id: 'walmart',
    store_ids_used: ['aldi', 'walmart'],
    summary_text: 'Avocado toast, Caesar salad, and a slow cooker pot roast to end the week.',
  },
];

export const SEEDED_MEALS = [
  // ── MONDAY ──────────────────────────────────────────────────────────────────
  {
    meal_id: 'meal_mon_b',
    day_plan_id: 'dp_mon',
    meal_type: 'Breakfast',
    meal_name: 'Oatmeal + Bananas + Yogurt',
    meal_description: 'Steel-cut oats topped with sliced bananas and a side of plain yogurt. Simple, filling, and budget-friendly.',
    servings: 4,
    estimated_total_cents: 325,
    estimated_per_serving_cents: 81,
    estimated_savings_cents: 80,
    prep_time_minutes: 5,
    best_store_id: 'aldi',
    store_ids_used: ['aldi'],
    why_picked: 'Aldi oats and bananas are among the lowest-cost breakfast options available this week. Matches your budget goal and quick-meal preference.',
    compliance_score: 88,
    compliance_label: 'Strong Match',
    goal_tags: ['budget', 'quick'],
  },
  {
    meal_id: 'meal_mon_l',
    day_plan_id: 'dp_mon',
    meal_type: 'Lunch',
    meal_name: 'Turkey Wraps + Salad',
    meal_description: 'Sliced turkey in whole wheat tortillas with romaine lettuce, tomato, and a light Caesar dressing. Side salad included.',
    servings: 4,
    estimated_total_cents: 625,
    estimated_per_serving_cents: 156,
    estimated_savings_cents: 120,
    prep_time_minutes: 15,
    best_store_id: 'publix',
    store_ids_used: ['publix'],
    why_picked: 'Publix deli turkey is on BOGO this week, making this one of the best protein-per-dollar lunches available.',
    compliance_score: 82,
    compliance_label: 'Strong Match',
    goal_tags: ['quick', 'protein'],
  },
  {
    meal_id: 'meal_mon_d',
    day_plan_id: 'dp_mon',
    meal_type: 'Dinner',
    meal_name: '7-Day Italian Family Feast',
    meal_description: 'Classic spaghetti Bolognese with ground beef, marinara, garlic bread, and a Caesar salad. Feeds the whole family.',
    servings: 4,
    estimated_total_cents: 1800,
    estimated_per_serving_cents: 450,
    estimated_savings_cents: 320,
    prep_time_minutes: 20,
    best_store_id: 'publix',
    store_ids_used: ['publix', 'aldi'],
    why_picked: 'Italian pantry staples split across Publix BOGO pasta sauce and Aldi ground beef cut the cost significantly while keeping quality high.',
    compliance_score: 76,
    compliance_label: 'Strong Match',
    goal_tags: ['family', 'budget'],
  },

  // ── TUESDAY ─────────────────────────────────────────────────────────────────
  {
    meal_id: 'meal_tue_b',
    day_plan_id: 'dp_tue',
    meal_type: 'Breakfast',
    meal_name: 'Scrambled Eggs + Toast',
    meal_description: 'Fluffy scrambled eggs with buttered whole wheat toast. Quick protein-forward start to the day.',
    servings: 4,
    estimated_total_cents: 280,
    estimated_per_serving_cents: 70,
    estimated_savings_cents: 60,
    prep_time_minutes: 10,
    best_store_id: 'aldi',
    store_ids_used: ['aldi'],
    why_picked: 'Aldi eggs are competitively priced and this meal is one of the fastest high-protein breakfasts available.',
    compliance_score: 85,
    compliance_label: 'Strong Match',
    goal_tags: ['protein', 'quick'],
  },
  {
    meal_id: 'meal_tue_l',
    day_plan_id: 'dp_tue',
    meal_type: 'Lunch',
    meal_name: 'Grilled Cheese + Tomato Soup',
    meal_description: 'Classic grilled cheese sandwiches paired with creamy tomato soup. Comfort food at a budget price.',
    servings: 4,
    estimated_total_cents: 550,
    estimated_per_serving_cents: 138,
    estimated_savings_cents: 100,
    prep_time_minutes: 15,
    best_store_id: 'aldi',
    store_ids_used: ['aldi'],
    why_picked: 'All ingredients sourced from Aldi for maximum savings. Bread, cheese, and canned soup are all Aldi-label items.',
    compliance_score: 72,
    compliance_label: 'Good Match',
    goal_tags: ['quick', 'budget'],
  },
  {
    meal_id: 'meal_tue_d',
    day_plan_id: 'dp_tue',
    meal_type: 'Dinner',
    meal_name: 'Chicken Stir Fry with Rice',
    meal_description: 'Stir-fried chicken breast with bell peppers, broccoli, snap peas, and soy-ginger sauce over steamed jasmine rice.',
    servings: 4,
    estimated_total_cents: 1650,
    estimated_per_serving_cents: 413,
    estimated_savings_cents: 230,
    prep_time_minutes: 25,
    best_store_id: 'publix',
    store_ids_used: ['publix'],
    why_picked: 'Publix chicken breast is on promotion this week. High protein density, fast cook time, and full veggie coverage in one dish.',
    compliance_score: 91,
    compliance_label: 'Best Match',
    goal_tags: ['protein', 'quick'],
  },

  // ── WEDNESDAY ───────────────────────────────────────────────────────────────
  {
    meal_id: 'meal_wed_b',
    day_plan_id: 'dp_wed',
    meal_type: 'Breakfast',
    meal_name: 'Yogurt Parfait + Granola',
    meal_description: 'Layered Greek yogurt with granola, mixed berries, and a drizzle of honey. Light and nutritious.',
    servings: 4,
    estimated_total_cents: 360,
    estimated_per_serving_cents: 90,
    estimated_savings_cents: 70,
    prep_time_minutes: 5,
    best_store_id: 'aldi',
    store_ids_used: ['aldi'],
    why_picked: 'Aldi Greek yogurt and granola provide excellent value. This meal meets both budget and quick-prep goals.',
    compliance_score: 79,
    compliance_label: 'Strong Match',
    goal_tags: ['budget', 'quick'],
  },
  {
    meal_id: 'meal_wed_l',
    day_plan_id: 'dp_wed',
    meal_type: 'Lunch',
    meal_name: 'Tuna Salad Wraps',
    meal_description: 'Canned tuna mixed with celery, mayo, and lemon juice wrapped in flour tortillas with mixed greens.',
    servings: 4,
    estimated_total_cents: 580,
    estimated_per_serving_cents: 145,
    estimated_savings_cents: 90,
    prep_time_minutes: 10,
    best_store_id: 'walmart',
    store_ids_used: ['walmart'],
    why_picked: 'Walmart Great Value canned tuna offers the best price per serving for a protein-rich lunch option.',
    compliance_score: 80,
    compliance_label: 'Strong Match',
    goal_tags: ['protein', 'quick'],
  },
  {
    meal_id: 'meal_wed_d',
    day_plan_id: 'dp_wed',
    meal_type: 'Dinner',
    meal_name: 'Beef Tacos',
    meal_description: 'Seasoned ground beef tacos with shredded cheese, salsa, sour cream, lettuce, and warm corn tortillas.',
    servings: 4,
    estimated_total_cents: 1680,
    estimated_per_serving_cents: 420,
    estimated_savings_cents: 250,
    prep_time_minutes: 20,
    best_store_id: 'publix',
    store_ids_used: ['publix', 'walmart'],
    why_picked: 'Ground beef on deal at Publix this week. Walmart taco toppings bring the total cost down while maintaining variety.',
    compliance_score: 74,
    compliance_label: 'Good Match',
    goal_tags: ['family', 'budget'],
  },

  // ── THURSDAY ────────────────────────────────────────────────────────────────
  {
    meal_id: 'meal_thu_b',
    day_plan_id: 'dp_thu',
    meal_type: 'Breakfast',
    meal_name: 'Banana Pancakes',
    meal_description: 'Fluffy pancakes made with ripe bananas, eggs, and oat flour. Naturally sweet with no added sugar needed.',
    servings: 4,
    estimated_total_cents: 420,
    estimated_per_serving_cents: 105,
    estimated_savings_cents: 80,
    prep_time_minutes: 15,
    best_store_id: 'aldi',
    store_ids_used: ['aldi'],
    why_picked: 'Uses pantry staples from Aldi. Bananas purchased earlier in the week reduce waste and cost.',
    compliance_score: 68,
    compliance_label: 'Good Match',
    goal_tags: ['budget', 'family'],
  },
  {
    meal_id: 'meal_thu_l',
    day_plan_id: 'dp_thu',
    meal_type: 'Lunch',
    meal_name: 'Greek Salad + Pita',
    meal_description: 'Fresh Greek salad with cucumber, olives, feta, red onion, and tomato served with warm pita bread.',
    servings: 4,
    estimated_total_cents: 720,
    estimated_per_serving_cents: 180,
    estimated_savings_cents: 140,
    prep_time_minutes: 10,
    best_store_id: 'publix',
    store_ids_used: ['publix'],
    why_picked: 'Publix feta and olives are on weekly deal. This lunch satisfies vegetable intake goals and keeps carbs moderate.',
    compliance_score: 83,
    compliance_label: 'Strong Match',
    goal_tags: ['protein', 'budget'],
  },
  {
    meal_id: 'meal_thu_d',
    day_plan_id: 'dp_thu',
    meal_type: 'Dinner',
    meal_name: 'Salmon with Roasted Vegetables',
    meal_description: 'Herb-crusted salmon fillets roasted alongside asparagus, cherry tomatoes, and baby potatoes with olive oil and garlic.',
    servings: 4,
    estimated_total_cents: 1800,
    estimated_per_serving_cents: 450,
    estimated_savings_cents: 260,
    prep_time_minutes: 25,
    best_store_id: 'publix',
    store_ids_used: ['publix'],
    why_picked: 'Atlantic salmon is at its weekly low at Publix. Omega-3 rich, high protein, and a strong match for your nutrition goals.',
    compliance_score: 86,
    compliance_label: 'Strong Match',
    goal_tags: ['protein', 'family'],
  },

  // ── FRIDAY ──────────────────────────────────────────────────────────────────
  {
    meal_id: 'meal_fri_b',
    day_plan_id: 'dp_fri',
    meal_type: 'Breakfast',
    meal_name: 'French Toast + Fresh Fruit',
    meal_description: 'Thick-cut French toast with cinnamon and vanilla, served with a bowl of seasonal fresh fruit.',
    servings: 4,
    estimated_total_cents: 390,
    estimated_per_serving_cents: 98,
    estimated_savings_cents: 70,
    prep_time_minutes: 10,
    best_store_id: 'aldi',
    store_ids_used: ['aldi'],
    why_picked: 'Uses bread from earlier in the week to minimize waste. Aldi eggs and fruit keep cost minimal.',
    compliance_score: 73,
    compliance_label: 'Good Match',
    goal_tags: ['budget', 'quick'],
  },
  {
    meal_id: 'meal_fri_l',
    day_plan_id: 'dp_fri',
    meal_type: 'Lunch',
    meal_name: 'BLT Sandwich + Chips',
    meal_description: 'Classic bacon, lettuce, and tomato on toasted sourdough with a side of kettle chips.',
    servings: 4,
    estimated_total_cents: 670,
    estimated_per_serving_cents: 168,
    estimated_savings_cents: 100,
    prep_time_minutes: 10,
    best_store_id: 'walmart',
    store_ids_used: ['walmart'],
    why_picked: 'Walmart bacon pricing beats other stores this week. Quick to assemble — ideal Friday lunch to save energy for cooking dinner.',
    compliance_score: 69,
    compliance_label: 'Good Match',
    goal_tags: ['quick', 'budget'],
  },
  {
    meal_id: 'meal_fri_d',
    day_plan_id: 'dp_fri',
    meal_type: 'Dinner',
    meal_name: 'Chicken Tikka Masala',
    meal_description: 'Tender chicken pieces in a rich tomato-cream sauce with basmati rice and warm naan bread.',
    servings: 4,
    estimated_total_cents: 1800,
    estimated_per_serving_cents: 450,
    estimated_savings_cents: 250,
    prep_time_minutes: 30,
    best_store_id: 'publix',
    store_ids_used: ['publix'],
    why_picked: 'Publix has Tikka Masala sauce on promotion. Pairs perfectly with Publix chicken for a restaurant-quality Friday dinner.',
    compliance_score: 88,
    compliance_label: 'Strong Match',
    goal_tags: ['protein', 'family'],
  },

  // ── SATURDAY ────────────────────────────────────────────────────────────────
  {
    meal_id: 'meal_sat_b',
    day_plan_id: 'dp_sat',
    meal_type: 'Breakfast',
    meal_name: 'Veggie Omelette',
    meal_description: 'Three-egg omelette filled with sauteed spinach, mushrooms, onions, and bell peppers with shredded cheese.',
    servings: 4,
    estimated_total_cents: 480,
    estimated_per_serving_cents: 120,
    estimated_savings_cents: 90,
    prep_time_minutes: 15,
    best_store_id: 'aldi',
    store_ids_used: ['aldi'],
    why_picked: 'Aldi vegetables and eggs are the strongest value match for a protein-rich weekend breakfast.',
    compliance_score: 85,
    compliance_label: 'Strong Match',
    goal_tags: ['protein', 'budget'],
  },
  {
    meal_id: 'meal_sat_l',
    day_plan_id: 'dp_sat',
    meal_type: 'Lunch',
    meal_name: 'Club Sandwich + Soup',
    meal_description: 'Triple-decker club sandwiches with turkey, ham, bacon, and Swiss cheese served with a bowl of vegetable soup.',
    servings: 4,
    estimated_total_cents: 840,
    estimated_per_serving_cents: 210,
    estimated_savings_cents: 150,
    prep_time_minutes: 15,
    best_store_id: 'publix',
    store_ids_used: ['publix'],
    why_picked: 'Publix deli meats are at their weekly deal. The club sandwich delivers strong protein coverage at a fair price.',
    compliance_score: 77,
    compliance_label: 'Strong Match',
    goal_tags: ['protein', 'family'],
  },
  {
    meal_id: 'meal_sat_d',
    day_plan_id: 'dp_sat',
    meal_type: 'Dinner',
    meal_name: 'BBQ Pork Ribs',
    meal_description: 'Slow-baked pork ribs with BBQ sauce, coleslaw, corn on the cob, and baked beans. Weekend family feast.',
    servings: 4,
    estimated_total_cents: 1800,
    estimated_per_serving_cents: 450,
    estimated_savings_cents: 250,
    prep_time_minutes: 45,
    best_store_id: 'publix',
    store_ids_used: ['publix', 'walmart'],
    why_picked: 'Publix pork ribs are on BOGO this weekend. Walmart BBQ sauce and sides complete the meal cost-effectively.',
    compliance_score: 71,
    compliance_label: 'Good Match',
    goal_tags: ['family', 'budget'],
  },

  // ── SUNDAY ──────────────────────────────────────────────────────────────────
  {
    meal_id: 'meal_sun_b',
    day_plan_id: 'dp_sun',
    meal_type: 'Breakfast',
    meal_name: 'Avocado Toast',
    meal_description: 'Smashed avocado on sourdough toast with cherry tomatoes, red pepper flakes, and a squeeze of lemon.',
    servings: 4,
    estimated_total_cents: 399,
    estimated_per_serving_cents: 100,
    estimated_savings_cents: 50,
    prep_time_minutes: 10,
    best_store_id: 'walmart',
    store_ids_used: ['walmart'],
    why_picked: 'Walmart avocados are the best value this week. Simple prep, good fat content, and fits the quick-meal goal.',
    compliance_score: 78,
    compliance_label: 'Strong Match',
    goal_tags: ['quick', 'budget'],
  },
  {
    meal_id: 'meal_sun_l',
    day_plan_id: 'dp_sun',
    meal_type: 'Lunch',
    meal_name: 'Caesar Salad + Soup',
    meal_description: 'Crisp romaine Caesar salad with croutons and Parmesan paired with a cup of tomato basil soup.',
    servings: 4,
    estimated_total_cents: 600,
    estimated_per_serving_cents: 150,
    estimated_savings_cents: 80,
    prep_time_minutes: 10,
    best_store_id: 'aldi',
    store_ids_used: ['aldi'],
    why_picked: 'Aldi romaine and Parmesan are budget-friendly. Light Sunday lunch before a heavier dinner is a strong planning choice.',
    compliance_score: 80,
    compliance_label: 'Strong Match',
    goal_tags: ['quick', 'budget'],
  },
  {
    meal_id: 'meal_sun_d',
    day_plan_id: 'dp_sun',
    meal_type: 'Dinner',
    meal_name: 'Slow Cooker Pot Roast',
    meal_description: 'Tender chuck roast slow-cooked with carrots, potatoes, celery, onion, and beef broth. Sunday comfort classic.',
    servings: 4,
    estimated_total_cents: 1600,
    estimated_per_serving_cents: 400,
    estimated_savings_cents: 90,
    prep_time_minutes: 20,
    best_store_id: 'walmart',
    store_ids_used: ['walmart'],
    why_picked: 'Walmart chuck roast is competitively priced. Slow cooker method minimizes active prep time while maximizing flavor.',
    compliance_score: 84,
    compliance_label: 'Strong Match',
    goal_tags: ['family', 'budget'],
  },
];

export const SEEDED_STORES = [
  {
    store_id: 'publix',
    store_name: 'Publix',
    store_initial: 'PX',
    store_total_cents: 9240,
    store_savings_cents: 1875,
    store_role: 'Dinner ingredients, BOGO savings, Family meal bundles',
    items_count: 18,
    meals_supported: ['Monday Dinner', 'Tuesday Lunch', 'Thursday Dinner', 'Friday Dinner'],
    deal_valid_until: 'May 17',
  },
  {
    store_id: 'aldi',
    store_name: 'Aldi',
    store_initial: 'AL',
    store_total_cents: 6420,
    store_savings_cents: 740,
    store_role: 'Breakfast staples, Protein basics, Pantry items',
    items_count: 14,
    meals_supported: ['Monday Breakfast', 'Tuesday Breakfast', 'Wednesday Breakfast'],
    deal_valid_until: 'May 17',
  },
  {
    store_id: 'walmart',
    store_name: 'Walmart',
    store_initial: 'WM',
    store_total_cents: 3709,
    store_savings_cents: 315,
    store_role: 'Household items, Backup staples, Pantry stock',
    items_count: 8,
    meals_supported: ['Wednesday Lunch', 'Friday Lunch', 'Sunday Dinner'],
    deal_valid_until: 'May 17',
  },
];

export const SEEDED_NUTRITION = [
  // Monday
  {
    meal_id: 'meal_mon_b',
    estimated_calories: 420,
    estimated_protein_g: 18,
    estimated_carbs_g: 52,
    estimated_fat_g: 12,
    estimated_sodium_mg: 280,
    estimated_sugar_g: 14,
    nutrition_confidence: 'estimated',
    nutrition_disclaimer_required: true,
  },
  {
    meal_id: 'meal_mon_l',
    estimated_calories: 580,
    estimated_protein_g: 32,
    estimated_carbs_g: 48,
    estimated_fat_g: 18,
    estimated_sodium_mg: 620,
    estimated_sugar_g: 6,
    nutrition_confidence: 'estimated',
    nutrition_disclaimer_required: true,
  },
  {
    meal_id: 'meal_mon_d',
    estimated_calories: 880,
    estimated_protein_g: 34,
    estimated_carbs_g: 82,
    estimated_fat_g: 28,
    estimated_sodium_mg: 740,
    estimated_sugar_g: 8,
    nutrition_confidence: 'estimated',
    nutrition_disclaimer_required: true,
  },
  // Tuesday
  {
    meal_id: 'meal_tue_b',
    estimated_calories: 380,
    estimated_protein_g: 26,
    estimated_carbs_g: 30,
    estimated_fat_g: 16,
    estimated_sodium_mg: 340,
    estimated_sugar_g: 4,
    nutrition_confidence: 'estimated',
    nutrition_disclaimer_required: true,
  },
  {
    meal_id: 'meal_tue_l',
    estimated_calories: 520,
    estimated_protein_g: 18,
    estimated_carbs_g: 56,
    estimated_fat_g: 22,
    estimated_sodium_mg: 680,
    estimated_sugar_g: 10,
    nutrition_confidence: 'estimated',
    nutrition_disclaimer_required: true,
  },
  {
    meal_id: 'meal_tue_d',
    estimated_calories: 720,
    estimated_protein_g: 48,
    estimated_carbs_g: 58,
    estimated_fat_g: 14,
    estimated_sodium_mg: 580,
    estimated_sugar_g: 10,
    nutrition_confidence: 'estimated',
    nutrition_disclaimer_required: true,
  },
  // Wednesday
  {
    meal_id: 'meal_wed_b',
    estimated_calories: 440,
    estimated_protein_g: 20,
    estimated_carbs_g: 58,
    estimated_fat_g: 10,
    estimated_sodium_mg: 160,
    estimated_sugar_g: 18,
    nutrition_confidence: 'estimated',
    nutrition_disclaimer_required: true,
  },
  {
    meal_id: 'meal_wed_l',
    estimated_calories: 490,
    estimated_protein_g: 36,
    estimated_carbs_g: 40,
    estimated_fat_g: 14,
    estimated_sodium_mg: 560,
    estimated_sugar_g: 4,
    nutrition_confidence: 'estimated',
    nutrition_disclaimer_required: true,
  },
  {
    meal_id: 'meal_wed_d',
    estimated_calories: 760,
    estimated_protein_g: 30,
    estimated_carbs_g: 68,
    estimated_fat_g: 26,
    estimated_sodium_mg: 820,
    estimated_sugar_g: 10,
    nutrition_confidence: 'estimated',
    nutrition_disclaimer_required: true,
  },
  // Thursday
  {
    meal_id: 'meal_thu_b',
    estimated_calories: 460,
    estimated_protein_g: 14,
    estimated_carbs_g: 72,
    estimated_fat_g: 12,
    estimated_sodium_mg: 220,
    estimated_sugar_g: 20,
    nutrition_confidence: 'estimated',
    nutrition_disclaimer_required: true,
  },
  {
    meal_id: 'meal_thu_l',
    estimated_calories: 480,
    estimated_protein_g: 16,
    estimated_carbs_g: 52,
    estimated_fat_g: 20,
    estimated_sodium_mg: 740,
    estimated_sugar_g: 6,
    nutrition_confidence: 'estimated',
    nutrition_disclaimer_required: true,
  },
  {
    meal_id: 'meal_thu_d',
    estimated_calories: 640,
    estimated_protein_g: 52,
    estimated_carbs_g: 28,
    estimated_fat_g: 22,
    estimated_sodium_mg: 420,
    estimated_sugar_g: 4,
    nutrition_confidence: 'estimated',
    nutrition_disclaimer_required: true,
  },
  // Friday
  {
    meal_id: 'meal_fri_b',
    estimated_calories: 500,
    estimated_protein_g: 14,
    estimated_carbs_g: 70,
    estimated_fat_g: 14,
    estimated_sodium_mg: 300,
    estimated_sugar_g: 16,
    nutrition_confidence: 'estimated',
    nutrition_disclaimer_required: true,
  },
  {
    meal_id: 'meal_fri_l',
    estimated_calories: 620,
    estimated_protein_g: 24,
    estimated_carbs_g: 52,
    estimated_fat_g: 28,
    estimated_sodium_mg: 860,
    estimated_sugar_g: 8,
    nutrition_confidence: 'estimated',
    nutrition_disclaimer_required: true,
  },
  {
    meal_id: 'meal_fri_d',
    estimated_calories: 780,
    estimated_protein_g: 46,
    estimated_carbs_g: 62,
    estimated_fat_g: 24,
    estimated_sodium_mg: 660,
    estimated_sugar_g: 12,
    nutrition_confidence: 'estimated',
    nutrition_disclaimer_required: true,
  },
  // Saturday
  {
    meal_id: 'meal_sat_b',
    estimated_calories: 400,
    estimated_protein_g: 28,
    estimated_carbs_g: 20,
    estimated_fat_g: 22,
    estimated_sodium_mg: 360,
    estimated_sugar_g: 4,
    nutrition_confidence: 'estimated',
    nutrition_disclaimer_required: true,
  },
  {
    meal_id: 'meal_sat_l',
    estimated_calories: 660,
    estimated_protein_g: 38,
    estimated_carbs_g: 54,
    estimated_fat_g: 26,
    estimated_sodium_mg: 920,
    estimated_sugar_g: 6,
    nutrition_confidence: 'estimated',
    nutrition_disclaimer_required: true,
  },
  {
    meal_id: 'meal_sat_d',
    estimated_calories: 920,
    estimated_protein_g: 44,
    estimated_carbs_g: 60,
    estimated_fat_g: 38,
    estimated_sodium_mg: 780,
    estimated_sugar_g: 20,
    nutrition_confidence: 'estimated',
    nutrition_disclaimer_required: true,
  },
  // Sunday
  {
    meal_id: 'meal_sun_b',
    estimated_calories: 360,
    estimated_protein_g: 10,
    estimated_carbs_g: 44,
    estimated_fat_g: 18,
    estimated_sodium_mg: 280,
    estimated_sugar_g: 4,
    nutrition_confidence: 'estimated',
    nutrition_disclaimer_required: true,
  },
  {
    meal_id: 'meal_sun_l',
    estimated_calories: 420,
    estimated_protein_g: 16,
    estimated_carbs_g: 46,
    estimated_fat_g: 16,
    estimated_sodium_mg: 580,
    estimated_sugar_g: 8,
    nutrition_confidence: 'estimated',
    nutrition_disclaimer_required: true,
  },
  {
    meal_id: 'meal_sun_d',
    estimated_calories: 760,
    estimated_protein_g: 44,
    estimated_carbs_g: 52,
    estimated_fat_g: 28,
    estimated_sodium_mg: 560,
    estimated_sugar_g: 8,
    nutrition_confidence: 'estimated',
    nutrition_disclaimer_required: true,
  },
];

export const SEEDED_USER_PROFILE = {
  selected_goals: ['high_protein', 'budget', 'quick_meals'],
  nutrition_filters: ['high_protein', 'budget'],
  calorie_target: '600-1000',
  protein_target: 30,
  food_preferences: [],
  allergy_flags: [],
  favorite_stores: ['publix', 'aldi'],
  multi_store_preference: true,
  brand_flexibility: 'sometimes',
};
